### ISSUE TITLE
Mace not doing extra damage?

### ISSUE THREAD

**Issue by Ravings1** [Jusey1/TrialsTowers#2]
Are there any known incompatibilities? The mace nor the density enchantment seem to work with the damage ramp up.
[latest.log](https://github.com/Jusey1/TrialsTowers/files/15281657/latest.log)

**Comment by Ravings1** [comment]
After doing some quick testing, it seems Random Crits prevents the mace from gaining increased damage from height fallen.

**Comment by Jusey1** [comment]
That's intentional since the extra damage is only on a critical damage after falling. Since if you disable vanilla critical hits, then that's on you in all honesty.
